# version: '3.8'

services:
  app:
    build: ./backend
    container_name: swiswim_backend
    restart: no
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_started

  db:
    image: 'postgres:latest'
    ports:
      - "127.0.0.1:5433:5432"
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
