"""Unique_constraint_exercise

Revision ID: 05c164a2849a
Revises: ef6716c32228
Create Date: 2026-02-11 11:34:38.540430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c164a2849a'
down_revision: Union[str, Sequence[str], None] = 'ef6716c32228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exercise_name-distance', 'exercises', ['name', 'distance_meters'])
    op.drop_index(op.f('unique_name_version'), table_name='training_templates')
    op.create_index('unique_name-version', 'training_templates', ['name', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_name-version', table_name='training_templates')
    op.create_index(op.f('unique_name_version'), 'training_templates', ['name', 'version'], unique=True)
    op.drop_constraint('uq_exercise_name-distance', 'exercises', type_='unique')
    # ### end Alembic commands ###
