"""TrainingStep reformat

Revision ID: 36f64f79f8cb
Revises: b3a1f7c9d2e4
Create Date: 2026-02-13 19:21:05.517128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36f64f79f8cb'
down_revision: Union[str, Sequence[str], None] = 'b3a1f7c9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'custom_pool_size')
    op.drop_column('workouts', 'planned_start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('planned_start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('workouts', sa.Column('custom_pool_size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
