"""Model_improvements

Revision ID: 610c85ed67fc
Revises: 1c839382ecae
Create Date: 2026-02-11 18:07:36.887491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610c85ed67fc'
down_revision: Union[str, Sequence[str], None] = '1c839382ecae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = postgresql.ENUM('user', 'admin', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', name='user_role'), server_default='user', nullable=False))
    op.drop_constraint(op.f('uq_user_email-full_name'), 'users', type_='unique')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_email-full_name'), 'users', ['email', 'full_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'role')
    op.drop_column('refresh_tokens', 'expires_at')
    user_role_enum = postgresql.ENUM('user', 'admin', name='user_role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
