"""Sessions_to_Workouts

Revision ID: 78f69734f852
Revises: a050827937eb
Create Date: 2026-02-12 17:52:12.212025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f69734f852'
down_revision: Union[str, Sequence[str], None] = 'a050827937eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workouts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_template_id', sa.UUID(), nullable=False),
    sa.Column('pool_size_meters', sa.Integer(), nullable=False),
    sa.Column('custom_pool_size', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('in_progress', 'completed', 'abandoned', 'synced', name='workout_status'), server_default='in_progress', nullable=False),
    sa.Column('planned_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_distance_planned', sa.Integer(), nullable=False),
    sa.Column('total_distance_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['training_template_id'], ['training_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workout-actual_start_time', 'workouts', ['actual_start_time'], unique=False)
    op.create_index('idx_workout-status', 'workouts', ['status'], unique=False)
    op.create_index('idx_workout-user_id', 'workouts', ['user_id'], unique=False)
    op.create_table('workout_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'skipped', name='workout_step_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'step_number', name='unique_workout_step')
    )
    op.create_index('idx_workout_step-workout_id', 'workout_steps', ['workout_id'], unique=False)
    op.drop_index(op.f('idx_session_step-session_id'), table_name='session_steps')
    op.drop_table('session_steps')
    op.drop_index(op.f('idx_session-actual_start_time'), table_name='sessions')
    op.drop_index(op.f('idx_session-status'), table_name='sessions')
    op.drop_index(op.f('idx_session-user_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('training_template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pool_size_meters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_pool_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('in_progress', 'completed', 'abandoned', 'synced', name='session_status'), server_default=sa.text("'in_progress'::session_status"), autoincrement=False, nullable=False),
    sa.Column('planned_start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('actual_start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('actual_end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_distance_planned', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_distance_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_duration_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['training_template_id'], ['training_templates.id'], name=op.f('sessions_training_template_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('idx_session-user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_session-status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('idx_session-actual_start_time'), 'sessions', ['actual_start_time'], unique=False)
    op.create_table('session_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('distance_meters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'skipped', name='session_step_status'), server_default=sa.text("'pending'::session_step_status"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('session_steps_exercise_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('session_steps_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_steps_pkey')),
    sa.UniqueConstraint('session_id', 'step_number', name=op.f('unique_session_step'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_session_step-session_id'), 'session_steps', ['session_id'], unique=False)
    op.drop_index('idx_workout_step-workout_id', table_name='workout_steps')
    op.drop_table('workout_steps')
    op.drop_index('idx_workout-user_id', table_name='workouts')
    op.drop_index('idx_workout-status', table_name='workouts')
    op.drop_index('idx_workout-actual_start_time', table_name='workouts')
    op.drop_table('workouts')
    # ### end Alembic commands ###
