"""Unique_constraints_all

Revision ID: cf7975e52d9b
Revises: 05c164a2849a
Create Date: 2026-02-11 11:37:45.098008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7975e52d9b'
down_revision: Union[str, Sequence[str], None] = '05c164a2849a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('unique_session_step'), table_name='session_steps')
    op.create_unique_constraint('unique_session_step', 'session_steps', ['session_id', 'step_number'])
    op.drop_index(op.f('unique_training_step'), table_name='training_steps')
    op.create_unique_constraint('unique_training_step', 'training_steps', ['training_template_id', 'step_number'])
    op.drop_index(op.f('unique_name-version'), table_name='training_templates')
    op.create_unique_constraint('unique_name-version', 'training_templates', ['name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name-version', 'training_templates', type_='unique')
    op.create_index(op.f('unique_name-version'), 'training_templates', ['name', 'version'], unique=True)
    op.drop_constraint('unique_training_step', 'training_steps', type_='unique')
    op.create_index(op.f('unique_training_step'), 'training_steps', ['training_template_id', 'step_number'], unique=True)
    op.drop_constraint('unique_session_step', 'session_steps', type_='unique')
    op.create_index(op.f('unique_session_step'), 'session_steps', ['session_id', 'step_number'], unique=True)
    # ### end Alembic commands ###
