"""schema_v01

Revision ID: ef6716c32228
Revises: 
Create Date: 2026-02-09 20:07:52.432164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef6716c32228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('style', postgresql.ENUM('freestyle', 'backstroke', 'breaststroke', 'butterfly', 'mixed', name='swimming_style'), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_style', 'exercises', ['style'], unique=False)
    op.create_table('training_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='training_level'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_template-is_active', 'training_templates', ['is_active'], unique=False)
    op.create_index('idx_training_template-level', 'training_templates', ['level'], unique=False)
    op.create_index('unique_name_version', 'training_templates', ['name', 'version'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferred_pool_size', sa.Integer(), server_default='25', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token-user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_template_id', sa.UUID(), nullable=False),
    sa.Column('pool_size_meters', sa.Integer(), nullable=False),
    sa.Column('custom_pool_size', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('in_progress', 'completed', 'abandoned', 'synced', name='session_status'), server_default='in_progress', nullable=False),
    sa.Column('planned_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('total_distance_planned', sa.Integer(), nullable=False),
    sa.Column('total_distance_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_template_id'], ['training_templates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session-actual_start_time', 'sessions', ['actual_start_time'], unique=False)
    op.create_index('idx_session-status', 'sessions', ['status'], unique=False)
    op.create_index('idx_session-user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('training_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('training_template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_template_id'], ['training_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_step-training_template', 'training_steps', ['training_template_id'], unique=False)
    op.create_index('unique_training_step', 'training_steps', ['training_template_id', 'step_number'], unique=True)
    op.create_table('session_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'skipped', name='session_step_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_step-session_id', 'session_steps', ['session_id'], unique=False)
    op.create_index('unique_session_step', 'session_steps', ['session_id', 'step_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_session_step', table_name='session_steps')
    op.drop_index('idx_session_step-session_id', table_name='session_steps')
    op.drop_table('session_steps')
    op.drop_index('unique_training_step', table_name='training_steps')
    op.drop_index('idx_training_step-training_template', table_name='training_steps')
    op.drop_table('training_steps')
    op.drop_index('idx_session-user_id', table_name='sessions')
    op.drop_index('idx_session-status', table_name='sessions')
    op.drop_index('idx_session-actual_start_time', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_token_hash', table_name='refresh_tokens')
    op.drop_index('idx_token-user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('unique_name_version', table_name='training_templates')
    op.drop_index('idx_training_template-level', table_name='training_templates')
    op.drop_index('idx_training_template-is_active', table_name='training_templates')
    op.drop_table('training_templates')
    op.drop_index('idx_style', table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
